### ISSUE TITLE
기존 hosts 정보 유실

### ISSUE THREAD

**Issue by return0927** [parkkyuhyeon/block_site#1]
현재의 코드를 적용하면, `Code1`에서 `links.txt`의 정보를 시스템 파일인 `hosts`에 덮어씌우게 되는데, 이 때 백업을 하지 않고 `Code2`에서 복원 시에 `hosts.txt`에 들어있는 `hosts`의 template만 들어가게 되어 원래 `hosts`를 사용하는 유저는 기존 데이터를 유실하게 됩니다.

- `Code1`
https://github.com/parkkyuhyeon/block_site/blob/29e997852578640bb94d2c3888d06bf19ec9cef2/block_site.py#L6-L12

- `Code2`
https://github.com/parkkyuhyeon/block_site/blob/29e997852578640bb94d2c3888d06bf19ec9cef2/block_site.py#L15-L20

**Comment by return0927** [comment]
기존의 `hosts`를 백업하는 코드를 block_site.py#L6의 case에 추가해야할 것 같습니다

**Comment by parkkyuhyeon** [comment]
수정했습니다. 빠른 지적 감사드립니다.
